export default {
  lastUpdated: "2025-04-01",
  currency: "EUR",
  categories: [
    "Sport",
    "Ville",
    "Outdoor",
    "Professionnel",
    "Cérémonie",
    "Casual",
    "Enfant",
    "Été",
    "Saison",
    "Maison",
    "Danse"
  ],
  homeCategories: [
    {
      id: 1,
      name: "Sneakers",
      image: "https://picsum.photos/id/237/600/400",
      description: "Les meilleures sneakers du moment",
      slug: "sneakers"
    },
    {
      id: 2,
      name: "Streetwear",
      image: "https://picsum.photos/id/238/600/400",
      description: "Vêtements et accessoires streetwear",
      slug: "streetwear"
    },
    {
      id: 3,
      name: "Électronique",
      image: "https://picsum.photos/id/239/600/400",
      description: "Consoles, jeux vidéo et plus",
      slug: "electronique"
    },
    {
      id: 4,
      name: "Cartes à collectionner",
      image: "https://picsum.photos/id/240/600/400",
      description: "Pokémon, Magic et autres",
      slug: "cartes"
    }
  ],
  brands: [
    "RunFast",
    "CityWalk",
    "SportPro",
    "TrekMaster",
    "SafeStep",
    "GalaStar",
    "UrbanFlex",
    "KidStep",
    "SummerFlex",
    "RainGuard",
    "HomeComfort",
    "DancePro",
    "MedStyle",
    "ItalianLeather"
  ],
  products: [
    {
      id: 1,
      name: 'Chaussure de course',
      description: 'Confort ultime - Légèreté - Amortissement optimal pour vos séances de running',
      price: 120,
      image: 'https://picsum.photos/seed/Chaussure_de_course/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_course_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_course_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_course_4/500/500',
        'https://picsum.photos/seed/Chaussure_de_course_5/500/500',
      ],
      colors: ['Rouge', 'Noir', 'Bleu'],
      sizes: [38, 39, 40, 41, 42, 43, 44, 45],
      brand: 'RunFast',
      category: 'Sport',
      inStock: true,
      rating: 4.7,
      reviews: 128,
      discount: 10,
      isNew: false,
      materials: ['Textile respirant', 'Semelle caoutchouc', 'Mousse EVA'],
      features: ['Respirabilité', 'Amorti', 'Adhérence'],
      tags: ['running', 'athlétisme', 'fitness']
    },
    {
      id: 2,
      name: 'Chaussure de ville',
      description: 'Cuir véritable - Confort ultime - Design élégant pour toutes occasions',
      price: 89.99,
      image: 'https://picsum.photos/seed/Chaussure_de_ville/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_ville_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_ville_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_ville_4/500/500',
      ],
      colors: ['Noir', 'Marron', 'Beige'],
      sizes: [39, 40, 41, 42, 43, 44],
      brand: 'CityWalk',
      category: 'Ville',
      inStock: true,
      rating: 4.5,
      reviews: 96,
      discount: 0,
      isNew: false,
      materials: ['Cuir pleine fleur', 'Semelle intérieure en cuir', 'Semelle extérieure en caoutchouc'],
      features: ['Élégance', 'Durabilité', 'Confort quotidien'],
      tags: ['business', 'formel', 'quotidien']
    },
    {
      id: 3,
      name: 'Chaussure de sport',
      description: 'Confort ultime - Légèreté - Polyvalence pour tous types d\'activités sportives',
      price: 99.99,
      image: 'https://picsum.photos/seed/Chaussure_de_sport/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_sport_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_sport_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_sport_4/500/500',
        'https://picsum.photos/seed/Chaussure_de_sport_5/500/500',
        'https://picsum.photos/seed/Chaussure_de_sport_6/500/500',
      ],
      colors: ['Blanc', 'Noir', 'Gris', 'Bleu'],
      sizes: [38, 39, 40, 41, 42, 43, 44],
      brand: 'SportPro',
      category: 'Sport',
      inStock: true,
      rating: 3,
      reviews: 150,
      discount: 5,
      isNew: true,
      materials: ['Textile respirant', 'Semelle caoutchouc', 'Mousse amortissante'],
      features: ['Polyvalence', 'Confort', 'Style'],
      tags: ['fitness', 'gym', 'loisir']
    },
    {
      id: 4,
      name: 'Chaussure de randonnée',
      description: 'Confort ultime - Légèreté - Imperméable et résistante pour vos treks',
      price: 149.99,
      image: 'https://picsum.photos/seed/Chaussure_de_randonnee/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_randonnee_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_randonnee_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_randonnee_4/500/500',
      ],
      colors: ['Vert', 'Marron', 'Gris'],
      sizes: [39, 40, 41, 42, 43, 44, 45, 46],
      brand: 'TrekMaster',
      category: 'Outdoor',
      inStock: true,
      rating: 4.8,
      reviews: 86,
      discount: 0,
      isNew: false,
      materials: ['Cuir hydrofuge', 'Membrane imperméable', 'Semelle Vibram'],
      features: ['Imperméabilité', 'Grip', 'Protection'],
      tags: ['randonnée', 'montagne', 'trekking']
    },
    {
      id: 5,
      name: 'Chaussure de sécurité',
      description: 'Confort ultime - Légèreté - Protection renforcée avec embout acier',
      price: 199.99,
      image: 'https://picsum.photos/seed/Chaussure_de_securite/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_securite_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_securite_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_securite_4/500/500',
      ],
      colors: ['Noir', 'Jaune'],
      sizes: [39, 40, 41, 42, 43, 44, 45, 46, 47],
      brand: 'SafeStep',
      category: 'Professionnel',
      inStock: false,
      rating: 4.6,
      reviews: 62,
      discount: 0,
      isNew: false,
      materials: ['Cuir traité', 'Coque acier', 'Semelle anti-perforation'],
      features: ['Protection', 'Durabilité', 'Certification S3'],
      tags: ['sécurité', 'chantier', 'industrie']
    },
    {
      id: 6,
      name: 'Chaussure de soirée',
      description: 'Confort ultime - Légèreté - Élégance et raffinement pour vos événements',
      price: 79.99,
      image: 'https://picsum.photos/seed/Chaussure_de_soiree/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_de_soiree_2/500/500',
        'https://picsum.photos/seed/Chaussure_de_soiree_3/500/500',
        'https://picsum.photos/seed/Chaussure_de_soiree_4/500/500',
      ],
      colors: ['Noir', 'Bleu marine', 'Bordeaux'],
      sizes: [39, 40, 41, 42, 43, 44],
      brand: 'GalaStar',
      category: 'Cérémonie',
      inStock: true,
      rating: 4.4,
      reviews: 74,
      discount: 0,
      isNew: false,
      materials: ['Cuir verni', 'Satin', 'Semelle cuir'],
      features: ['Élégance', 'Confort', 'Finitions soignées'],
      tags: ['mariage', 'cérémonie', 'soirée']
    },
    {
      id: 7,
      name: 'Basket streetwear',
      description: 'Style urbain - Confort quotidien - Design tendance',
      price: 89.99,
      image: 'https://picsum.photos/seed/Basket_streetwear/500/500',
      images: [
        'https://picsum.photos/seed/Basket_streetwear_2/500/500',
        'https://picsum.photos/seed/Basket_streetwear_3/500/500',
        'https://picsum.photos/seed/Basket_streetwear_4/500/500',
        'https://picsum.photos/seed/Basket_streetwear_5/500/500',
        'https://picsum.photos/seed/Basket_streetwear_6/500/500',
      ],
      colors: ['Blanc', 'Noir', 'Rouge', 'Bleu'],
      sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
      brand: 'UrbanFlex',
      category: 'Casual',
      inStock: true,
      rating: 4.5,
      reviews: 218,
      discount: 15,
      isNew: true,
      materials: ['Cuir synthétique', 'Textile', 'Semelle EVA'],
      features: ['Style', 'Confort', 'Polyvalence'],
      tags: ['streetwear', 'tendance', 'urbain']
    },
    {
      id: 8,
      name: 'Chaussure enfant',
      description: 'Robuste - Légère - Adaptée pour les activités de vos enfants',
      price: 49.99,
      image: 'https://picsum.photos/seed/Chaussure_enfant/500/500',
      images: [
        'https://picsum.photos/seed/Chaussure_enfant_2/500/500',
        'https://picsum.photos/seed/Chaussure_enfant_3/500/500',
        'https://picsum.photos/seed/Chaussure_enfant_4/500/500',
      ],
      colors: ['Rouge', 'Bleu', 'Rose', 'Vert'],
      sizes: [28, 29, 30, 31, 32, 33, 34, 35],
      brand: 'KidStep',
      category: 'Enfant',
      inStock: true,
      rating: 4.7,
      reviews: 103,
      discount: 0,
      isNew: true,
      materials: ['Cuir synthétique', 'Textile', 'Semelle flexible'],
      features: ['Résistant', 'Flexible', 'Facile à enfiler'],
      tags: ['enfant', 'école', 'confort']
    },
    {
      id: 9,
      name: 'Sandales d\'été',
      description: 'Légères et aérées - Parfaites pour les journées chaudes',
      price: 59.99,
      image: 'https://picsum.photos/seed/Sandales_ete/500/500',
      images: [
        'https://picsum.photos/seed/Sandales_ete_2/500/500',
        'https://picsum.photos/seed/Sandales_ete_3/500/500',
        'https://picsum.photos/seed/Sandales_ete_4/500/500',
      ],
      colors: ['Beige', 'Marron', 'Bleu', 'Noir'],
      sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
      brand: 'SummerFlex',
      category: 'Été',
      inStock: true,
      rating: 4.4,
      reviews: 89,
      discount: 15,
      isNew: false,
      materials: ['Cuir', 'Liège', 'Caoutchouc'],
      features: ['Respirabilité', 'Légèreté', 'Confort'],
      tags: ['été', 'plage', 'vacances']
    },
    {
      id: 10,
      name: 'Bottes de pluie',
      description: 'Imperméables - Style urbain pour les jours de pluie',
      price: 69.99,
      image: 'https://picsum.photos/seed/Bottes_pluie/500/500',
      images: [
        'https://picsum.photos/seed/Bottes_pluie_2/500/500',
        'https://picsum.photos/seed/Bottes_pluie_3/500/500',
        'https://picsum.photos/seed/Bottes_pluie_4/500/500',
      ],
      colors: ['Noir', 'Bleu marine', 'Rouge', 'Vert'],
      sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
      brand: 'RainGuard',
      category: 'Saison',
      inStock: true,
      rating: 4.2,
      reviews: 76,
      discount: 0,
      isNew: true,
      materials: ['Caoutchouc naturel', 'Coton', 'PVC'],
      features: ['Imperméabilité', 'Facilité d\'entretien', 'Antidérapant'],
      tags: ['pluie', 'automne', 'imperméable']
    },
    {
      id: 11,
      name: 'Mules confort',
      description: 'Détente et repos - Confort absolu pour la maison',
      price: 39.99,
      image: 'https://picsum.photos/seed/Mules_confort/500/500',
      images: [
        'https://picsum.photos/seed/Mules_confort_2/500/500',
        'https://picsum.photos/seed/Mules_confort_3/500/500',
        'https://picsum.photos/seed/Mules_confort_4/500/500',
      ],
      colors: ['Gris', 'Beige', 'Rose', 'Bleu ciel'],
      sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
      brand: 'HomeComfort',
      category: 'Maison',
      inStock: true,
      rating: 4.9,
      reviews: 156,
      discount: 0,
      isNew: false,
      materials: ['Mousse à mémoire de forme', 'Coton', 'Microfibre'],
      features: ['Ultra-confort', 'Antidérapant', 'Lavable'],
      tags: ['intérieur', 'détente', 'confort']
    },
    {
      id: 12,
      name: 'Chaussures de danse',
      description: 'Flexibilité maximale - Pour tous types de danse',
      price: 85.99,
      image: 'https://picsum.photos/seed/Chaussures_danse/500/500',
      images: [
        'https://picsum.photos/seed/Chaussures_danse_2/500/500',
        'https://picsum.photos/seed/Chaussures_danse_3/500/500',
        'https://picsum.photos/seed/Chaussures_danse_4/500/500',
      ],
      colors: ['Noir', 'Beige', 'Rouge'],
      sizes: [35, 36, 37, 38, 39, 40, 41, 42],
      brand: 'DancePro',
      category: 'Danse',
      inStock: true,
      rating: 4.6,
      reviews: 94,
      discount: 0,
      isNew: false,
      materials: ['Cuir souple', 'Semelle cuir', 'Tissus élastiques'],
      features: ['Flexibilité', 'Légèreté', 'Adhérence'],
      tags: ['danse', 'art', 'performance']
    },
    {
      id: 13,
      name: 'Espadrilles',
      description: 'Style méditerranéen - Légères et tendance',
      price: 45.99,
      image: 'https://picsum.photos/seed/Espadrilles/500/500',
      images: [
        'https://picsum.photos/seed/Espadrilles_2/500/500',
        'https://picsum.photos/seed/Espadrilles_3/500/500',
        'https://picsum.photos/seed/Espadrilles_4/500/500',
      ],
      colors: ['Beige', 'Bleu marine', 'Rouge', 'Rayé'],
      sizes: [36, 37, 38, 39, 40, 41, 42, 43, 44],
      brand: 'MedStyle',
      category: 'Été',
      inStock: true,
      rating: 4.3,
      reviews: 112,
      discount: 10,
      isNew: false,
      materials: ['Toile', 'Jute', 'Corde'],
      features: ['Style', 'Légèreté', 'Respirabilité'],
      tags: ['été', 'vacances', 'casual']
    },
    {
      id: 14,
      name: 'Mocassins premium',
      description: 'Cuir italien - Élégance intemporelle',
      price: 129.99,
      image: 'https://picsum.photos/seed/Mocassins_premium/500/500',
      images: [
        'https://picsum.photos/seed/Mocassins_premium_2/500/500',
        'https://picsum.photos/seed/Mocassins_premium_3/500/500',
        'https://picsum.photos/seed/Mocassins_premium_4/500/500',
        'https://picsum.photos/seed/Mocassins_premium_5/500/500',
      ],
      colors: ['Marron', 'Noir', 'Bordeaux', 'Bleu marine'],
      sizes: [39, 40, 41, 42, 43, 44, 45],
      brand: 'ItalianLeather',
      category: 'Ville',
      inStock: true,
      rating: 4.8,
      reviews: 67,
      discount: 0,
      isNew: true,
      materials: ['Cuir pleine fleur italien', 'Semelle cuir', 'Doublure cuir'],
      features: ['Élégance', 'Confort', 'Qualité supérieure'],
      tags: ['luxe', 'business', 'élégance']
    }
  ],
  featuredProducts: [1, 3, 7, 11, 14],
  bestSellers: [3, 7, 2, 11, 13],
  filters: {
    priceRanges: [
      {id: 1, name: "Moins de 50€", min: 0, max: 50},
      {id: 2, name: "50€ - 100€", min: 50, max: 100},
      {id: 3, name: "100€ - 150€", min: 100, max: 150},
      {id: 4, name: "Plus de 150€", min: 150, max: null}
    ],
    allSizes: [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
    allColors: ["Rouge", "Noir", "Bleu", "Blanc", "Gris", "Vert", "Marron", "Beige", "Jaune", "Bleu marine", "Bordeaux", "Rose", "Bleu ciel", "Rayé"]
  },
  shipping: {
    freeShippingThreshold: 80,
    standardShipping: 5.99,
    expressShipping: 12.99
  },
  contactInfo: {
    email: "contact@chaussures-store.com",
    phone: "+33 1 23 45 67 89",
    address: "123 Avenue de la Mode, 75001 Paris, France"
  }
}